

app:
  version: 0.0.1

spring:
  profiles:
    active: dev
  application:
    name: discovery-server
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0 # only for testing purpose, switch back to 0.1 for production code
#  security:
#    user:
#      name: eureka
#      password: password
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: 'false'
    fetch-registry: 'false'
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8761